language: java

sudo: true

jdk: openjdk8

services:
 - docker



jobs:
  include:
    - stage: test
      name: "repairnator-integration-test"
      install: ./.travis/travis-before.sh
      script: travis_wait 40 ./.travis/travis-run.sh

